Repository DeveloperAcademy-POSTECH/MC2-Team14-OXY, pull requests merged in 2022-06, with the labels that each got.

#3 feat: develop 브랜치 추가
  TeamOXY/TeamOXY/ContentView.swift
Labels: enhancement

#4 #2 Config: 프로젝트 폴더 구조 설정
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
Labels: enhancement

#5 Update README.md
  README.md
Labels: documentation

#8 [Merge] 템플릿 파일
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  README.md
Labels: feature, 에코

#19 [Merge] Pretendard 폰트 설정
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Black.dataset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Black.dataset/Pretendard-Black.otf
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Bold.dataset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Bold.dataset/Pretendard-Bold.otf
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-ExtraBold.dataset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-ExtraBold.dataset/Pretendard-ExtraBold.otf
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-ExtraLight.dataset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-ExtraLight.dataset/Pretendard-ExtraLight.otf
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Light.dataset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Light.dataset/Pretendard-Light.otf
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Medium.dataset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Medium.dataset/Pretendard-Medium.otf
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Regular.dataset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Regular.dataset/Pretendard-Regular.otf
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-SemiBold.dataset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-SemiBold.dataset/Pretendard-SemiBold.otf
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Thin.dataset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Fonts/Pretendard-Thin.dataset/Pretendard-Thin.otf
  TeamOXY/TeamOXY/ContentView.swift
Labels: 에코, chore

#20 [Merge] 초기 환경 설정
  .gitattributes
  README.md
  TeamOXY/.DS_Store
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Contents.json
  TeamOXY/TeamOXY/Constants/.gitkeep
  TeamOXY/TeamOXY/ContentView.swift
  TeamOXY/TeamOXY/Extensions/.gitkeep
  TeamOXY/TeamOXY/Fonts/Pretendard-Black.otf
  TeamOXY/TeamOXY/Fonts/Pretendard-Bold.otf
  TeamOXY/TeamOXY/Fonts/Pretendard-ExtraBold.otf
  TeamOXY/TeamOXY/Fonts/Pretendard-ExtraLight.otf
  TeamOXY/TeamOXY/Fonts/Pretendard-Light.otf
  TeamOXY/TeamOXY/Fonts/Pretendard-Medium.otf
  TeamOXY/TeamOXY/Fonts/Pretendard-Regular.otf
  TeamOXY/TeamOXY/Fonts/Pretendard-SemiBold.otf
  TeamOXY/TeamOXY/Fonts/Pretendard-Thin.otf
  TeamOXY/TeamOXY/Info.plist
  TeamOXY/TeamOXY/Model/.gitkeep
  TeamOXY/TeamOXY/TeamOXYApp.swift
  TeamOXY/TeamOXY/View/.gitkeep
  TeamOXY/TeamOXY/View/HomeView.swift
  TeamOXY/TeamOXY/ViewModel/.gitkeep
Labels: 에코, chore

#21 Feat/#15/home view UI
  .DS_Store
  TeamOXY/.DS_Store
  TeamOXY/HomeView.swift
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/.DS_Store
  TeamOXY/TeamOXY/Assets.xcassets/.DS_Store
  TeamOXY/TeamOXY/Assets.xcassets/Logo.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Logo.imageset/Logo-1.png
  TeamOXY/TeamOXY/Assets.xcassets/Logo.imageset/Logo-2.png
  TeamOXY/TeamOXY/Assets.xcassets/Logo.imageset/Logo.png
  TeamOXY/TeamOXY/Assets.xcassets/🏠.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/🏠.imageset/🏡-1.png
  TeamOXY/TeamOXY/Assets.xcassets/🏠.imageset/🏡-2.png
  TeamOXY/TeamOXY/Assets.xcassets/🏠.imageset/🏡.png
  TeamOXY/TeamOXY/Assets.xcassets/🚪.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/🚪.imageset/🚪-1.png
  TeamOXY/TeamOXY/Assets.xcassets/🚪.imageset/🚪-2.png
  TeamOXY/TeamOXY/Assets.xcassets/🚪.imageset/🚪.png
  TeamOXY/TeamOXY/ColorExtension.swift
  TeamOXY/TeamOXY/Colors.xcassets/Contents.json
  TeamOXY/TeamOXY/Colors.xcassets/DarkGray1.colorset/Contents.json
  TeamOXY/TeamOXY/Colors.xcassets/Gray1.colorset/Contents.json
  TeamOXY/TeamOXY/Colors.xcassets/LightGray1.colorset/Contents.json
  TeamOXY/TeamOXY/Colors.xcassets/PrimaryBlue.colorset/Contents.json
  TeamOXY/TeamOXY/Colors.xcassets/PrimarySkyBlue.colorset/Contents.json
  TeamOXY/TeamOXY/Preview Content/.DS_Store
  TeamOXY/TeamOXY/View/.DS_Store
Labels: feature, design, 쑤

#26 [Merge] #1 카드 제스처 및 미팅룸 뷰
  TeamOXY/.DS_Store
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/TeamOXYApp.swift
  TeamOXY/TeamOXY/View/CardDeckView.swift
  TeamOXY/TeamOXY/View/CardZoneView.swift
  TeamOXY/TeamOXY/View/MeetingRoomView.swift
  TeamOXY/TeamOXY/View/TempCardView.swift
  TeamOXY/TeamOXY/View/TestCardView.swift
  TeamOXY/TeamOXY/View/TestGestureView.swift
Labels: feature, design, 다니

#31 Feature/#11 card gesture
  TeamOXY/.DS_Store
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/TeamOXYApp.swift
  TeamOXY/TeamOXY/View/CardDeckView.swift
  TeamOXY/TeamOXY/View/CardZoneView.swift
  TeamOXY/TeamOXY/View/HomeView.swift
  TeamOXY/TeamOXY/View/MeetingRoomView.swift
  TeamOXY/TeamOXY/View/TempCardView.swift
  TeamOXY/TeamOXY/View/TestCardView.swift
  TeamOXY/TeamOXY/View/TestGestureView.swift
Labels: feature, design, 다니

#30 [Feature] #25 공용 컴포넌트 생성 & HomeView 리팩토링
  TeamOXY/HomeView.swift
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Assets.xcassets/🏡.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/🏡.imageset/🏡-1.png
  TeamOXY/TeamOXY/Assets.xcassets/🏡.imageset/🏡-2.png
  TeamOXY/TeamOXY/Assets.xcassets/🏡.imageset/🏡.png
  TeamOXY/TeamOXY/Assets.xcassets/🚪.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/🚪.imageset/🚪-1.png
  TeamOXY/TeamOXY/Assets.xcassets/🚪.imageset/🚪-2.png
  TeamOXY/TeamOXY/Assets.xcassets/🚪.imageset/🚪.png
  TeamOXY/TeamOXY/Components/RoundButton.swift
  TeamOXY/TeamOXY/Extensions/String+ButtonImageName.swift
Labels: feature, refactor, 에코

#35 [Merge] #12 반응 이모지 애니메이션 구현
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/View/EmojiReactionView.swift
  TeamOXY/TeamOXY/View/FancyButtonViewModel.swift
  TeamOXY/TeamOXY/View/TestView.swift
Labels: feature, 니로

#38 [Merge] #37 CreateMeetingRoomView UI
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Components/RoundButton.swift
  TeamOXY/TeamOXY/Constants/FieldType.swift
  TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
  TeamOXY/TeamOXY/View/HomeView.swift
Labels: feature, design, 에코

#40 [Merge] #39 QRCodeView UI
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/View/QRCode/QRCode.swift
  TeamOXY/TeamOXY/View/QRCode/QRCodeView.swift
Labels: feature, design, 에코

#44 Feature/#44 break time view UI
  TeamOXY/.DS_Store
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: design

#47 [Merge] #36 중복 가능한 반응 애니메이션 구현
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/TeamOXYApp.swift
  TeamOXY/TeamOXY/View/EmojiReactionView.swift
  TeamOXY/TeamOXY/ViewModel/EmojiViewModel.swift
Labels: feature, design, 니로

#48 [merge] #45 timer view update
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/View/BreakTimeView.swift
  TeamOXY/TeamOXY/View/CircularTimerView.swift
  TeamOXY/TeamOXY/View/TimeSetView.swift
  TeamOXY/TeamOXY/View/Timer/BreakTimeView.swift
  TeamOXY/TeamOXY/View/Timer/CircularTimerView.swift
  TeamOXY/TeamOXY/View/Timer/TimeSetView.swift
Labels: feature, design

#55 [Merge] #46 FinishTopicView UI 구현
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/View/FinishTopicView.swift
Labels: design, 다니

#57 [Merge] #56 QRCodeScanner 구현
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
  TeamOXY/TeamOXY/View/HomeView.swift
  TeamOXY/TeamOXY/View/QRCode/QRCode.swift
  TeamOXY/TeamOXY/View/QRCode/QRCodeView.swift
Labels: feature, 에코

#61 [Merge] #59 argument guide animation 구현
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/View/Arrows.swift
  TeamOXY/TeamOXY/View/EmojiReactionView.swift
  TeamOXY/TeamOXY/ViewModel/EmojiViewModel.swift
Labels: feature, 니로

#65 [Merge] #64 캐러셀버그수정 & 컴플리션로티추가
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/TeamOXYApp.swift
  TeamOXY/TeamOXY/View/CarouselView.swift
  TeamOXY/TeamOXY/View/EmojiReactionView.swift
  TeamOXY/TeamOXY/View/FinishTopicView.swift
  TeamOXY/TeamOXY/View/TopicCompletionView.swift
  TeamOXY/TeamOXY/ViewModel/CompletionViewModel.swift
Labels: bug, feature, 데이크

#69 [Merge] #67 Firebase Messaging & Functions
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/TeamOXYApp.swift
Labels: 에코, chore

#71 [Merge] User, Topic , Reaction 데이터 모델 생성
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Model/Reaction.swift
  TeamOXY/TeamOXY/Model/Topic.swift
  TeamOXY/TeamOXY/Model/User.swift
Labels: 에코, chore

#74 [Merge] #73 Firebase 환경 설정
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Constants/FirebaseConstants.swift
  TeamOXY/TeamOXY/Utils/FirebaseManager.swift
  TeamOXY/TeamOXY/Utils/generateRandomNickname.swift
Labels: 에코, chore

#76 [Merge] #66 Typography Extension 생성
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Extensions/TypographyExtension.swift
Labels: 에코, chore

#77 [Merge] #75 TestCardView 리팩토링 및 오류 수정
  TeamOXY/TeamOXY/View/TestCardView.swift
Labels: bug, refactor, 다니

#78 [Merge] #68 카드 shadow 디자인 수정 & 카드박스 디자인 수정 & extension추가 후 반응형화
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Colors.xcassets/ShadowGray.colorset/Contents.json
  TeamOXY/TeamOXY/Extensions/ColorExtension.swift
  TeamOXY/TeamOXY/Extensions/UIScreenExtension.swift
  TeamOXY/TeamOXY/View/CarouselView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/FinishTopicView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
  TeamOXY/TeamOXY/View/TransitionView/CompletedTopicView.swift
  TeamOXY/TeamOXY/ViewModel/CompletionViewModel.swift
  TeamOXY/TeamOXY/ViewModel/FinishTopicViewModel.swift
Labels: feature, design, 데이크

#81 [Merge] 방 생성 익명 로그인, 유저 정보 Firestore에 저장
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/TeamOXYApp.swift
  TeamOXY/TeamOXY/Utils/FirebaseManager.swift
  TeamOXY/TeamOXY/Utils/generateRandomNickname.swift
  TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
  TeamOXY/TeamOXY/View/Home/HomeView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
  TeamOXY/TeamOXY/ViewModel/MeetingRoomViewModel.swift
Labels: feature, 에코, chore

#82 [Merge] #79 FirebaseFirestore collection and document depth
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Constants/FirebaseConstants.swift
  TeamOXY/TeamOXY/Model/MeetingRoom.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
Labels: wontfix, 에코, chore

#84 [Merge] timer 기능 개선 완료
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Assets.xcassets/turnOffBeep.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/turnOffBeep.imageset/turnOffBeep-1.png
  TeamOXY/TeamOXY/Assets.xcassets/turnOffBeep.imageset/turnOffBeep-2.png
  TeamOXY/TeamOXY/Assets.xcassets/turnOffBeep.imageset/turnOffBeep.png
  TeamOXY/TeamOXY/Assets.xcassets/turnOnBeep.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/turnOnBeep.imageset/turnOnBeep-1.png
  TeamOXY/TeamOXY/Assets.xcassets/turnOnBeep.imageset/turnOnBeep-2.png
  TeamOXY/TeamOXY/Assets.xcassets/turnOnBeep.imageset/turnOnBeep.png
  TeamOXY/TeamOXY/Info.plist
  TeamOXY/TeamOXY/View/BreakTimeView.swift
  TeamOXY/TeamOXY/View/CircularTimerView.swift
  TeamOXY/TeamOXY/View/TimeSetView.swift
  TeamOXY/TeamOXY/View/TimerStatus.swift
Labels: feature, design, 케일리

#88 [Merge] #86 long press 햅틱 추가
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Utils/HapticManager.swift
  TeamOXY/TeamOXY/View/MeetingRoom/CarouselView.swift
Labels: feature, 다니

#90 [Merge] #83 MeetingRoom과 QR Code 연결
  TeamOXY/TeamOXY/Constants/FirebaseConstants.swift
  TeamOXY/TeamOXY/Model/MeetingRoom.swift
  TeamOXY/TeamOXY/Model/Reaction.swift
  TeamOXY/TeamOXY/Model/Topic.swift
  TeamOXY/TeamOXY/Model/User.swift
  TeamOXY/TeamOXY/Utils/FirebaseManager.swift
  TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
  TeamOXY/TeamOXY/View/Home/HomeView.swift
  TeamOXY/TeamOXY/View/Home/QRCode/QRCodeView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/EmojiReactionView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
  TeamOXY/TeamOXY/ViewModel/MeetingRoomViewModel.swift
Labels: feature, refactor, 에코

#92 [Merge] #91 리팩토링: Typography 적용 및 공용 컴포넌트 적용
  TeamOXY/TeamOXY/Components/RoundButton.swift
  TeamOXY/TeamOXY/Extensions/String+ButtonImageName.swift
  TeamOXY/TeamOXY/Extensions/TypographyExtension.swift
  TeamOXY/TeamOXY/View/BreakTime/BreakTimeView.swift
  TeamOXY/TeamOXY/View/BreakTime/CircularTimerView.swift
  TeamOXY/TeamOXY/View/BreakTime/TimeSetView.swift
  TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
  TeamOXY/TeamOXY/View/Home/HomeView.swift
  TeamOXY/TeamOXY/View/Home/QRCode/QRCodeView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/EmojiReactionView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/FinishTopicView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
Labels: refactor, 에코

#93 [Merge] 미팅룸 수정 & 코드정리
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Constants/CarouselViewConstants.swift
  TeamOXY/TeamOXY/TeamOXYApp.swift
  TeamOXY/TeamOXY/View/MeetingRoom/CarouselView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/FinishTopicView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
  TeamOXY/TeamOXY/ViewModel/CompletionViewModel.swift
Labels: design, 데이크

#100 [Merge] #96 leaveRoom() 메소드 개선 및 MeetingRoomViewModel 데이터 유지를 위한 리팩토링
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
  TeamOXY/TeamOXY/View/Home/HomeView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
  TeamOXY/TeamOXY/ViewModel/MeetingRoomViewModel.swift
Labels: feature, refactor, 에코

#101 [Merge] #97 Firebase Push Notification 보내는 로직 + FCM token 저장
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Config/Debug.xcconfig
  TeamOXY/TeamOXY/Config/Production.xcconfig
  TeamOXY/TeamOXY/Constants/FirebaseConstants.swift
  TeamOXY/TeamOXY/Info.plist
  TeamOXY/TeamOXY/Model/Topic.swift
  TeamOXY/TeamOXY/Model/User.swift
  TeamOXY/TeamOXY/Utils/SendNotification.swift
  TeamOXY/TeamOXY/ViewModel/MeetingRoomViewModel.swift
Labels: feature, 에코

#102 [Merge] #99 reaction emoji animation 로직 변경
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Model/ReactionEmoji.swift
  TeamOXY/TeamOXY/View/MeetingRoom/EmojiReactionView.swift
  TeamOXY/TeamOXY/ViewModel/EmojiViewModel.swift
Labels: feature, refactor, 니로

#105 [fix] Carddeck의 버그 수정
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/View/MeetingRoom/CarouselView.swift
Labels: bug, 데이크

#107 [Merge] #106 CarouselView 의 Card 를 누를시 발생하는 Reaction Animation 수정
  TeamOXY/TeamOXY/View/MeetingRoom/CarouselView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/EmojiReactionView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
  TeamOXY/TeamOXY/ViewModel/EmojiViewModel.swift
Labels: feature, 니로

#120 [Merge] #95 제안한 Topic을 받아서 통신하는 기능 구현
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Assets.xcassets/Card1.imageset/Card Copy 5@3x.png
  TeamOXY/TeamOXY/Assets.xcassets/Card1.imageset/Card1.png
  TeamOXY/TeamOXY/Assets.xcassets/Card1.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Card2.imageset/Card2.png
  TeamOXY/TeamOXY/Assets.xcassets/Card2.imageset/Card@3x.png
  TeamOXY/TeamOXY/Assets.xcassets/Card2.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Card3.imageset/Card Copy 11@3x.png
  TeamOXY/TeamOXY/Assets.xcassets/Card3.imageset/Card3.png
  TeamOXY/TeamOXY/Assets.xcassets/Card3.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Card4.imageset/Card Copy 8@3x.png
  TeamOXY/TeamOXY/Assets.xcassets/Card4.imageset/Card4.png
  TeamOXY/TeamOXY/Assets.xcassets/Card4.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Card5.imageset/Card Copy 6@3x.png
  TeamOXY/TeamOXY/Assets.xcassets/Card5.imageset/Card5.png
  TeamOXY/TeamOXY/Assets.xcassets/Card5.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Card6.imageset/Card6.png
  TeamOXY/TeamOXY/Assets.xcassets/Card6.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Logo.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Logo.imageset/Logo-1.png
  TeamOXY/TeamOXY/Assets.xcassets/Logo.imageset/Logo-2.png
  TeamOXY/TeamOXY/Assets.xcassets/Logo.imageset/Logo.png
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding1.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding1.imageset/Onboarding1-1.png
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding1.imageset/Onboarding1-2.png
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding1.imageset/Onboarding1.png
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding2.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding2.imageset/Onboarding2-1.png
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding2.imageset/Onboarding2-2.png
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding2.imageset/Onboarding2.png
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding3.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding3.imageset/Onboarding3-1.png
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding3.imageset/Onboarding3-2.png
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding3.imageset/Onboarding3.png
  TeamOXY/TeamOXY/Constants/FirebaseConstants.swift
  TeamOXY/TeamOXY/Extensions/String+TopicLableExtension.swift
  TeamOXY/TeamOXY/Model/Topic.swift
  TeamOXY/TeamOXY/Utils/FirebaseManager.swift
  TeamOXY/TeamOXY/Utils/generateRandomNickname.swift
  TeamOXY/TeamOXY/View/BreakTime/TimeSetView.swift
  TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
  TeamOXY/TeamOXY/View/Home/HomeView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/CarouselView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/FinishTopicView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
  TeamOXY/TeamOXY/ViewModel/CarouselViewModel.swift
  TeamOXY/TeamOXY/ViewModel/MeetingRoomViewModel.swift
Labels: feature, 에코

#116 [Merge] timer push notification
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  TeamOXY/TeamOXY/Constants/FirebaseConstants.swift
  TeamOXY/TeamOXY/Model/TimeModel.swift
  TeamOXY/TeamOXY/Model/TokenModel.swift
  TeamOXY/TeamOXY/Model/User.swift
  TeamOXY/TeamOXY/TeamOXYApp.swift
  TeamOXY/TeamOXY/Utils/FirebaseManager.swift
  TeamOXY/TeamOXY/Utils/NotificationManager.swift
  TeamOXY/TeamOXY/Utils/SendNotification.swift
  TeamOXY/TeamOXY/View/BreakTime/BreakTimeView.swift
  TeamOXY/TeamOXY/View/BreakTime/CircularTimerView.swift
  TeamOXY/TeamOXY/View/BreakTime/DeviceTestView.swift
  TeamOXY/TeamOXY/View/BreakTime/TimeSetView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/CarouselView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/FinishTopicView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
  TeamOXY/TeamOXY/ViewModel/MeetingRoomViewModel.swift
Labels: feature, 다니, 데이크

#125 [Merge] #122 Reaction Emoji Animation 수정 및 BackButton 삭제
  TeamOXY/TeamOXY/View/CreateMeetingRoomView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/CarouselView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/EmojiReactionView.swift
  TeamOXY/TeamOXY/View/MeetingRoom/MeetingRoomView.swift
  TeamOXY/TeamOXY/ViewModel/EmojiViewModel.swift
Labels: feature, design, refactor, 니로

#128 [Merge] 앱 아이콘 및 이름 변경
  TeamOXY/TeamOXY.xcodeproj/project.pbxproj
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/1024.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/120-1.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/120.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/180.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/40.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/58.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/60.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/80.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/87.png
  TeamOXY/TeamOXY/Assets.xcassets/AppIcon.appiconset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding1.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding2.imageset/Contents.json
  TeamOXY/TeamOXY/Assets.xcassets/Onboarding3.imageset/Contents.json
Labels: design
